Repository beCoditive/Becoditive-API, pull requests merged in 2021-05, with the labels that each got.

#7 banned a stupid site LMAO
  blocked/domains.js
Labels: enhancement

#8 Simply uuid() function
  Src/Controllers/Admin.js
Labels: enhancement

#9 Add automated unit testing
  Src/Utilities/functions.js
  jest.config.js
  package-lock.json
  package.json
  tests/Utilities/functions.test.js
Labels: Improvements, enhancement

#10 Simplify textToMorse and reverseString utilities
  Src/Utilities/functions.js
  tests/Utilities/functions.test.js
Labels: Improvements, enhancement

#11 Fix missing n letter handling in textToMorse
  Src/Utilities/functions.js
  tests/Utilities/functions.test.js
Labels: wontfix

#12 Clarify imports and functions
  Src/Controllers/Others.js
  Src/Controllers/Text.js
  Src/Utilities/functions.js
  tests/Utilities/functions.test.js
Labels: Improvements, enhancement

#14 Reformat whole codebase to use standardjs code styling
  .gitignore
  Src/Controllers/Admin.js
  Src/Controllers/Animals.js
  Src/Controllers/Games.js
  Src/Controllers/Images.js
  Src/Controllers/Meme.js
  Src/Controllers/Others.js
  Src/Controllers/Text.js
  Src/Controllers/View.js
  Src/Controllers/auth.js
  Src/Controllers/fake.js
  Src/Controllers/urlshortner.js
  Src/Data/words.js
  Src/Router/Animals.js
  Src/Router/Games.js
  Src/Router/Images.js
  Src/Router/Meme.js
  Src/Router/Others.js
  Src/Router/Text.js
  Src/Router/View.js
  Src/Router/admin.js
  Src/Router/fake.js
  Src/Router/urlshort.js
  Src/Utilities/auth.js
  Src/Utilities/functions.js
  assets/js/Counting.js
  assets/js/untitled.js
  blocked/blockedEmails.js
  blocked/domains.js
  blocked/extensions.js
  jest.config.js
  loadsampledata.js
  models/FakeCredit.js
  models/Uselessweb.js
  models/animals.js
  models/apikeys.js
  models/facts.js
  models/flirt.js
  models/insults.js
  models/jokes.js
  models/letsnotmeet.js
  models/memes.js
  models/neverhaveiever.js
  models/quotes.js
  models/songs.js
  models/trivia.js
  models/truthordare.js
  models/url-shortner.js
  models/wouldyourather.js
  package-lock.json
  package.json
  sample/animals.js
  sample/credits.js
  sample/flirts.js
  sample/insults.js
  sample/jokes.js
  server.js
  tests/Utilities/functions.test.js
Labels: Improvements, enhancement
